### ISSUE TITLE
more implementation README

### ISSUE THREAD

**Issue by resetLi** [peterwestuw/BottleSum#2]
Your paper is quite interesting, and thank you very much for providing the source code.
Can you perfect the README part with more implementation details? This will be of great help to those of us who are interested in this paper.

**Comment by peterwestuw** [comment]
The readme wasn't recently updated with extra information on running the code. Is there anything specific you would like to see included?

**Comment by makamkkumar** [comment]
Can you please provide more information on training as well as running the code. The instructions given are not self-explanatory. Thanks in advance.

**Comment by peterwestuw** [comment]
Would you be able to provide a little bit more detail? Specifically, which
of the two models are you trying to run and on which dataset? Thanks!

Peter

**Comment by makamkkumar** [comment]
I am trying to run it on CNNDM and DUC datasets
I am trying to run the both the codes

**Comment by makamkkumar** [comment]
I am trying to run it on CNNDM and DUC datasets
I am trying to run the both the codes
When I run the given sample code its does not give any output only blank file is present.

`python bottleEx_summarize.py -S1_path T1.txt -S2_path T2.txt -rem_words 3 -out_name TEx-output.txt`
Traceback (most recent call last):
  File "bottleEx_summarize.py", line 113, in <module>
    main()
  File "bottleEx_summarize.py", line 66, in main
    assert(len(examples_S1) == len(examples_S2))
AssertionError

`python bottleSelf_summarize.py -S1_path T1.txt -S2_path T2.txt -rem_words 3 -out_name TSelf-output.txt`

**Comment by peterwestuw** [comment]
Sorry for the late reply, I have been away from my work email for a couple
of weeks.

The problem in this case would seem to be that T1.txt and T2.txt contain
different numbers of lines, where they should contain the sentence to
summarize (s1) and the sentence that follows it in the original document
(s2).

If you're only interested in DUC and CNNDM, I have pregenerated outputs for
both of these sets (DUC2003 and DUC2004, and for CNNDM only the test set)
that I can send you directly. We don't include them on the git because we
don't own the input sets, but we are happy to share them through email.

Best,
Peter
